[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "9.0.0"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000
  publish = "public"
  targetPort = 5000
